EscuelaApp.Presentacion/Controllers/CoursesController.cs
using EscuelaApp.Dominio.DTO;
using EscuelaApp.Dominio.Interfaces;
using EscuelaApp.Persistencia.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Text;

namespace EscuelaApp.Presentacion.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICourses _repCourse;
        private readonly IDepartments _repDepartment;
        private readonly HttpClient _httpCliente;

        public CoursesController(ICourses repCourse, IDepartments repDepartment, HttpClient httpCliente)
        {
            _repCourse = repCourse;
            _repDepartment = repDepartment;
            _httpCliente = httpCliente;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            // TODO: Cambiar a utilizar API
            string url = "http://localhost:5182/api/Course/ObtenerTodo";

            // Realizar la petición
            HttpResponseMessage res = await _httpCliente.GetAsync(url);

            // Validar que la petición es exitosa
            if (res.IsSuccessStatusCode)
            {
                // Deserializar los datos
                List<CourseDTO> cursos = await res.Content.ReadFromJsonAsync<List<CourseDTO>>();
                return View(cursos);
            }
            else
            {
                StatusCode((int)res.StatusCode, "Error al obtener datos del curso");
                return View();
            }
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int id)
        {
            // TODO: CAMBIAR POR API
            var course = await _repCourse.obtenerCursosxId(id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public async Task<IActionResult> Create()
        {
            ViewData["DepartmentId"] = new SelectList(await _repDepartment.obtenerTodo(), "DepartmentId", "Name");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseId,Title,Credits,DepartmentId")] Course course)
        {
            int res = 0;
            if (ModelState.IsValid)
            {
                // TODO: Cambiar a utilizar API
                string url = "http://localhost:5182/api/Course/GuardarCurso";

                String jsonData = JsonConvert.SerializeObject(course);
                HttpContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                // Realizar la petición
                HttpResponseMessage response = await _httpCliente.PostAsync(url,content);

                // Validar que la petición es exitosa
                if (response.IsSuccessStatusCode)
                {
                    string resultdado = await response.Content.ReadAsStringAsync();
                }
                else
                {
                    //StatusCode((int)res.StatusCode, "Error al obtener datos del curso");
                    return View();
                }

                if (res == 1)
                {
                    // TempData["Mensaje"] = "Curso Insertado Correctamente";
                    ViewBag.Mensaje = "Curso Insertado Correctamente";
                    ViewBag.TipoMsg = "alert-primary";
                }
                else if (res == 3)
                {
                    ViewBag.Mensaje = $"Error al insertar. Ya existe un curso con el ID: {course.CourseId}";
                    ViewBag.TipoMsg = "alert-warning";
                }
                else
                {
                    // TempData["Mensaje"] = "Curso no ha sido guardado";
                    ViewBag.Mensaje = "Curso no ha sido guardado";
                    ViewBag.TipoMsg = "alert-danger";
                }
                // return RedirectToAction(nameof(Index));
                return View("Index", await _repCourse.obtenerTodo());
            }
            ViewData["DepartmentId"] = new SelectList(await _repDepartment.obtenerTodo(), "DepartmentId", "Name", course.DepartmentId);
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound(); // Handle case where id is null
            }

            int courseID = (int)id;
            var course = await _repCourse.obtenerCursosxId(courseID);

            if (course == null)
            {
                return NotFound(); // Handle case where course is not found
            }

            ViewData["DepartmentId"] = new SelectList(await _repDepartment.obtenerTodo(), "DepartmentId", "Name", course.DepartmentId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CourseId,Title,Credits,DepartmentId")] Course course)
        {
            if (id != course.CourseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                int res = await _repCourse.modificar(course);
                if (res == 1)
                {
                    // TempData["Mensaje"] = "Curso Insertado Correctamente";
                    ViewBag.Mensaje = "Curso Modificado Correctamente";
                    ViewBag.TipoMsg = "alert-primary";
                }
                else
                {
                    // TempData["Mensaje"] = "Curso no ha sido guardado";
                    ViewBag.Mensaje = "Curso no ha sido modificado";
                    ViewBag.TipoMsg = "alert-danger";
                }
                // return RedirectToAction(nameof(Index));
                return View("Index", await _repCourse.obtenerTodo());
            }
            ViewData["DepartmentId"] = new SelectList(await _repDepartment.obtenerTodo(), "DepartmentId", "Name", course.DepartmentId);
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _repCourse.obtenerCursosxId((int)id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _repCourse.obtenerCursosxId(id);

            if (course != null)
            {
                int res = await _repCourse.eliminar(course);
                if (res == 1)
                {
                    // TempData["Mensaje"] = "Curso Insertado Correctamente";
                    ViewBag.Mensaje = "Curso eliminado correctamente";
                    ViewBag.TipoMsg = "alert-primary";
                }
                else
                {
                    // TempData["Mensaje"] = "Curso no ha sido guardado";
                    ViewBag.Mensaje = "Curso no ha sido eliminado";
                    ViewBag.TipoMsg = "alert-danger";
                }
                // return RedirectToAction(nameof(Index));
                return View("Index", await _repCourse.obtenerTodo());
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

EscuelaApp.Presentacion/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EscuelaApp.Presentacion.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            ViewBag.Nombre = User.Identity?.Name;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        // Método para autenticar el usuario
        public async Task<IActionResult> Authenticate(string username, string password)
        {
            // Credenciales quemadas
            string hcUsername = "admin";
            string hcPassword = "admin123";
            string hcFullName = "Admin Admin";
            string hcRole = "administrador";

            // Verficiar las credenciales
            if (username == hcUsername && password == hcPassword)
            {
                // Crear los claims
                var claims = new List<Claim> {
                    new Claim(ClaimTypes.Name, hcFullName),
                    new Claim(ClaimTypes.NameIdentifier, hcUsername),
                    new Claim(ClaimTypes.Role, hcRole),
                    new Claim("ImagenUsuario", "https://png.pngtree.com/png-vector/20221203/ourmid/pngtree-cartoon-style-female-user-profile-icon-vector-illustraton-png-image_6489286.png")
                };

                // Crear la identidad del claim
                var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                // Autenticar el usuario
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity));

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Nombre de usuario o contraseña incorrecto");
                return View("Index");
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            // Sign out the user
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index");
        }


    }
}

EscuelaApp.Presentacion/Views/Shared/_Fila.cshtml
@using EscuelaApp.Dominio.DTO
@model CourseDTO

<tr>
    <td>@Html.DisplayFor(model => model.Title)</td>   <!-- Display Title -->
    <td>@Html.DisplayFor(model => model.Credits)</td>  <!-- Display Credits -->
    <td>@Html.DisplayFor(model => model.NombreDepartamento)</td> <!-- Display Department Name -->
    <td>
        <a asp-action="Edit" asp-route-id="@Model.CourseID">Edit</a> |
        <a asp-action="Details" asp-route-id="@Model.CourseID">Details</a> |
        <a asp-action="Delete" asp-route-id="@Model.CourseID">Delete</a>
    </td>
</tr>

EscuelaApp.Presentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EscuelaApp.Presentacion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EscuelaApp.Presentacion.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @if (@ViewBag.Nombre != null) { 
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EscuelaApp.Presentacion</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            @if (User.FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value == "administrador")
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Cursos</a>
                            }
                        </li>
                        <li class="nav-item">
                            <form method="post" asp-controller="Login" asp-action="Logout" class="nav-link text-dark" style="border: none; background: none; padding: 0;">
                                <button type="submit" class="btn btn-link text-dark" style="text-decoration: none;">Logout</button>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @* <p>@ViewBag.Nombre</p> *@
            <p>@User.Identity?.Name;</p>
            <p>@ViewBag.Role</p>
            @* <img src="@ViewBag.ImagenUsuario" id="imgUser"/> *@
            <img src="@User.FindFirst("ImagenUsuario")?.Value" id="imgUser" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EscuelaApp.Presentacion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>